### PR TITLE
Update `ipset` example

### PR DESCRIPTION
**Pull request by neon-dev**
The `ipset` script looked to be designed so that it could be executed repeatedly without issues, due to the `flush` statement and `-q` parameters.
However, doing so would generate duplicate iptables entries and temporarily disable the blocklist while new IPs were being fetched.
The new script solves these issues and uses apt-get to avoid a CLI warning when executed from cron.

If this new example script is too complex I would instead suggest removing the `ipset -q flush ipsum` line and make it more clear that it's not a ready-to-deploy script.

PS: Thanks for your work and the constant updates, greatly appreciated.

### CODE REVIEW

**Comment by neon-dev** [comment]
@stamparm I think something went wrong or did you not want to update the readme with the latest force-push?

**Comment by stamparm** [comment]
@neon-dev repository is force cleaned each 24h, to prevent the build up of data (because of diffs). please write here what you wanted to suggest

**Comment by neon-dev** [comment]
Yes I know, that's why I expected your latest force-push would include some changes in the readme, but it didn't.
This is the change I proposed:
https://github.com/neon-dev/ipsum/commit/66afab0bf698bc66e1a81b5013fb29c2402bee9a

**Comment by stamparm** [comment]
can you please elaborate: `However, doing so would generate duplicate iptables entries`?

also, i don't see any issue in `temporarily disable the blocklist while new IPs were being fetched`, so will just ignore that part TBH

**Comment by stamparm** [comment]
it is clear enough from the following that `it's not a ready-to-deploy script.`:

image

**Comment by stamparm** [comment]
image

**Comment by neon-dev** [comment]
> can you please elaborate
Of course:
It will only happen if you run the commands more than once, since `iptables -I` will insert a new rule each time.
And because of the reasons I explained in the PR description, to me the script to me implied it should be safe to execute it multiple times.

**Comment by stamparm** [comment]
with latest revision:
image

**Comment by neon-dev** [comment]
Looks good, thanks 👍

**Pull request closed without merging**
